site_name: My Docs
theme:
  name: "material"
  language: en
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          path: [javcrawler]
nav:
  - Home: index.md
  - Config:
      - Database configuration: config/database_config.md
      - Arguments: config/arguments.md
  - Database operations:
      - MySQL: dbop/mysql_op.md
  - Test:
      - hello: hello.md
      - world: world.md
